services:
  challenge-intake-search:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cis
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    
  postgres:
    image: pgvector/pgvector:pg17
    container_name: cis_postgres_rag
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - cis_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rag"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bootstrap_vector_ext:
    image: pgvector/pgvector:pg17
    container_name: cis_bootstrap_vector_ext
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      PGPASSWORD=postgres
      psql "postgresql://postgres@postgres:5432/rag" -v ON_ERROR_STOP=1
      -c "CREATE EXTENSION IF NOT EXISTS vector;"
    restart: "no"

volumes:
  cis_postgres_data: